#!/usr/bin/env python3
"""Generate Campaign I (Heir to the Empire) unit WML from one roster spec.

The generated files are committed. Re-run this tool after editing the roster
below; never hand-edit the generated ``units/hte_*.cfg`` files.

Why generated: every unit needs the same 13-state animation wiring that the
art queue validator checks literally (``image=units/<slug>/<state>.png``), and
movement/defense tables must stay consistent across the roster. Writing the
blocks out (rather than hiding them in a WML macro) keeps the art validator
and human reviewers able to see each reference.

Usage: python3 production/tools/gen_hte_units.py [--check]
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
UNITS_DIR = ROOT / "addons/Star_Wars_Thrawn_Trilogy/units"
HEADER = (
    "#textdomain wesnoth-Star_Wars_Thrawn_Trilogy\n"
    "# GENERATED by production/tools/gen_hte_units.py - do not edit by hand.\n"
)

TERRAINS = (
    "deep_water", "shallow_water", "reef", "swamp_water", "flat", "sand",
    "forest", "hills", "mountains", "village", "castle", "cave", "frozen",
    "unwalkable", "impassable", "fungus",
)
UNREACHABLE = 99

# Movement cost, defense (chance to be hit, lower is better), resistance
# (percent damage taken). Every terrain is listed explicitly so no value is
# inherited implicitly from an engine default.
MOVETYPES: dict[str, dict] = {
    "sw_infantry": {
        "doc": "Trained soldiers on foot.",
        "move": dict(deep_water=99, shallow_water=3, reef=2, swamp_water=3, flat=1, sand=2, forest=2, hills=2,
                     mountains=3, village=1, castle=1, cave=2, frozen=3, unwalkable=99, impassable=99, fungus=2),
        "defense": dict(deep_water=80, shallow_water=80, reef=70, swamp_water=80, flat=60, sand=70, forest=50,
                        hills=50, mountains=40, village=40, castle=40, cave=60, frozen=80, unwalkable=80,
                        impassable=80, fungus=50),
        "resist": dict(blade=100, pierce=100, impact=100, fire=100, cold=100, arcane=100),
    },
    "sw_armored_trooper": {
        "doc": "Plastoid-armored troopers: armor turns blades and glancing bolts but slows them on rough ground.",
        "move": dict(deep_water=99, shallow_water=3, reef=2, swamp_water=3, flat=1, sand=2, forest=2, hills=2,
                     mountains=3, village=1, castle=1, cave=2, frozen=3, unwalkable=99, impassable=99, fungus=2),
        "defense": dict(deep_water=80, shallow_water=80, reef=70, swamp_water=80, flat=60, sand=70, forest=50,
                        hills=50, mountains=50, village=40, castle=40, cave=60, frozen=80, unwalkable=80,
                        impassable=80, fungus=50),
        "resist": dict(blade=80, pierce=90, impact=100, fire=90, cold=100, arcane=100),
    },
    "sw_jedi": {
        "doc": "Force-trained warriors: hard to pin down anywhere.",
        "move": dict(deep_water=99, shallow_water=3, reef=2, swamp_water=2, flat=1, sand=2, forest=2, hills=2,
                     mountains=3, village=1, castle=1, cave=2, frozen=2, unwalkable=99, impassable=99, fungus=2),
        "defense": dict(deep_water=80, shallow_water=70, reef=60, swamp_water=70, flat=50, sand=60, forest=40,
                        hills=40, mountains=30, village=40, castle=30, cave=50, frozen=70, unwalkable=80,
                        impassable=80, fungus=40),
        "resist": dict(blade=100, pierce=100, impact=100, fire=100, cold=100, arcane=80),
    },
    "sw_wookiee": {
        "doc": "Wookiees climb and fight among great trees as easily as on open ground.",
        "move": dict(deep_water=99, shallow_water=3, reef=2, swamp_water=2, flat=1, sand=2, forest=1, hills=2,
                     mountains=3, village=1, castle=1, cave=2, frozen=2, unwalkable=99, impassable=99, fungus=2),
        "defense": dict(deep_water=80, shallow_water=80, reef=70, swamp_water=70, flat=60, sand=70, forest=30,
                        hills=50, mountains=40, village=40, castle=40, cave=60, frozen=70, unwalkable=80,
                        impassable=80, fungus=50),
        "resist": dict(blade=90, pierce=100, impact=90, fire=110, cold=80, arcane=100),
    },
    "sw_noghri": {
        "doc": "Noghri commandos move through cover with uncanny speed.",
        "move": dict(deep_water=99, shallow_water=3, reef=2, swamp_water=2, flat=1, sand=2, forest=1, hills=1,
                     mountains=2, village=1, castle=1, cave=1, frozen=2, unwalkable=99, impassable=99, fungus=1),
        "defense": dict(deep_water=80, shallow_water=70, reef=60, swamp_water=70, flat=50, sand=60, forest=40,
                        hills=40, mountains=40, village=40, castle=40, cave=40, frozen=70, unwalkable=80,
                        impassable=80, fungus=40),
        "resist": dict(blade=100, pierce=100, impact=100, fire=100, cold=100, arcane=100),
    },
    "sw_beast": {
        "doc": "Native predators at home in deep forest.",
        "move": dict(deep_water=99, shallow_water=3, reef=2, swamp_water=2, flat=1, sand=2, forest=1, hills=1,
                     mountains=2, village=1, castle=1, cave=2, frozen=2, unwalkable=99, impassable=99, fungus=2),
        "defense": dict(deep_water=80, shallow_water=80, reef=70, swamp_water=70, flat=60, sand=70, forest=40,
                        hills=50, mountains=40, village=60, castle=60, cave=60, frozen=70, unwalkable=80,
                        impassable=80, fungus=50),
        "resist": dict(blade=100, pierce=100, impact=100, fire=110, cold=100, arcane=100),
    },
    "sw_repulsor": {
        "doc": "Repulsorlift speeders: fast over open ground and water, clumsy among trees.",
        "move": dict(deep_water=2, shallow_water=1, reef=2, swamp_water=1, flat=1, sand=1, forest=3, hills=2,
                     mountains=99, village=1, castle=1, cave=3, frozen=1, unwalkable=99, impassable=99, fungus=3),
        "defense": dict(deep_water=70, shallow_water=60, reef=60, swamp_water=60, flat=60, sand=60, forest=70,
                        hills=60, mountains=80, village=60, castle=60, cave=70, frozen=60, unwalkable=80,
                        impassable=80, fungus=70),
        "resist": dict(blade=90, pierce=100, impact=110, fire=110, cold=120, arcane=120),
        "flies": False,
    },
    "sw_walker": {
        "doc": "Armored walkers: tough plating, big targets, vulnerable to ion fire and lightsabers.",
        "move": dict(deep_water=99, shallow_water=3, reef=3, swamp_water=4, flat=1, sand=2, forest=2, hills=2,
                     mountains=99, village=1, castle=1, cave=3, frozen=2, unwalkable=99, impassable=99, fungus=3),
        "defense": dict(deep_water=90, shallow_water=80, reef=80, swamp_water=80, flat=70, sand=70, forest=70,
                        hills=60, mountains=70, village=70, castle=60, cave=70, frozen=80, unwalkable=90,
                        impassable=90, fungus=70),
        "resist": dict(blade=50, pierce=60, impact=80, fire=70, cold=130, arcane=130),
    },
    "sw_starfighter": {
        "doc": "Starfighters: open space is their element; asteroid fields give cover but slow them.",
        "move": dict(deep_water=1, shallow_water=1, reef=1, swamp_water=1, flat=1, sand=1, forest=1, hills=1,
                     mountains=2, village=1, castle=1, cave=2, frozen=1, unwalkable=1, impassable=99, fungus=2),
        "defense": dict(deep_water=60, shallow_water=60, reef=60, swamp_water=60, flat=60, sand=60, forest=60,
                        hills=50, mountains=40, village=60, castle=60, cave=50, frozen=60, unwalkable=50,
                        impassable=80, fungus=50),
        "resist": dict(blade=100, pierce=100, impact=100, fire=100, cold=130, arcane=100),
        "flies": True,
    },
    "sw_capital": {
        "doc": "Capital ships: heavily shielded, slow, impossible to miss, and unable to enter asteroid fields.",
        "move": dict(deep_water=1, shallow_water=1, reef=1, swamp_water=1, flat=1, sand=1, forest=1, hills=2,
                     mountains=99, village=1, castle=1, cave=99, frozen=1, unwalkable=1, impassable=99, fungus=99),
        "defense": dict(deep_water=90, shallow_water=90, reef=90, swamp_water=90, flat=90, sand=90, forest=90,
                        hills=90, mountains=90, village=90, castle=90, cave=90, frozen=90, unwalkable=90,
                        impassable=90, fungus=90),
        "resist": dict(blade=40, pierce=50, impact=70, fire=60, cold=110, arcane=80),
        "flies": True,
    },
}

RACES = {
    "sw_myneyrshi": ("Myneyrshi", "Myneyrshi",
                     "Four-armed natives of Wayland's forests who hunt with spears and bows and distrust every outsider."),
    "sw_psadan": ("Psadan", "Psadans",
                  "Stocky Wayland natives with armored, plate-like skin, slow to anger and slower to forgive."),
    "sw_wookiee": ("Wookiee", "Wookiees",
                   "Tall, fur-covered natives of the forest world Kashyyyk, renowned for their strength, loyalty, and life debts."),
    "sw_noghri": ("Noghri", "Noghri",
                  "Gray-skinned commandos from the ravaged world Honoghr, bound in service to the Empire's Grand Admiral."),
    "sw_vornskr": ("Vornskr", "Vornskrs",
                   "Whip-tailed predators of Myrkr's forests that hunt by sensing the Force."),
}

# --- shared WML fragments --------------------------------------------------

YSALAMIRI_FREE = (
    "[filter]\n"
    "    # Force abilities fail inside a ysalamiri bubble. Scenarios that place\n"
    "    # ysalamiri store every affected hex in sw_ysalamiri_zone.\n"
    "    [not]\n"
    "        [filter_location]\n"
    "            find_in=sw_ysalamiri_zone\n"
    "        [/filter_location]\n"
    "    [/not]\n"
    "[/filter]"
)

def indent(text: str, spaces: int) -> str:
    pad = " " * spaces
    return "\n".join(pad + line if line.strip() else line for line in text.splitlines())


def force_agility() -> str:
    return (
        "[skirmisher]\n"
        "    id=sw_ability_force_agility\n"
        "    name= _ \"Force agility\"\n"
        "    female_name= _ \"female^Force agility\"\n"
        "    description= _ \"Guided by the Force, this unit ignores enemy zones of control. The ability fails inside a ysalamiri bubble.\"\n"
        "    affect_self=yes\n"
        + indent(YSALAMIRI_FREE, 4) + "\n"
        "[/skirmisher]"
    )


def force_healing() -> str:
    return (
        "[heals]\n"
        "    id=sw_ability_force_healing\n"
        "    value=6\n"
        "    max_value=6\n"
        "    affect_allies=yes\n"
        "    affect_self=no\n"
        "    poison=slowed\n"
        "    name= _ \"Force healing\"\n"
        "    description= _ \"Through the Force this unit restores up to 6 HP per turn to adjacent allies and slows poison. The ability fails inside a ysalamiri bubble.\"\n"
        "    [affect_adjacent]\n"
        "    [/affect_adjacent]\n"
        + indent(YSALAMIRI_FREE, 4) + "\n"
        "[/heals]"
    )


def keen_senses() -> str:
    return (
        "[dummy]\n"
        "    id=sw_ability_keen_senses\n"
        "    name= _ \"keen senses\"\n"
        "    description= _ \"Enemy Noghri within two hexes of this unit cannot hide.\"\n"
        "[/dummy]"
    )


def noghri_stealth() -> str:
    return (
        "[hides]\n"
        "    id=sw_ability_noghri_stealth\n"
        "    name= _ \"Noghri stealth\"\n"
        "    description= _ \"This unit is invisible to enemies while in forest or under cover of night, unless an enemy with keen senses is within two hexes. It is revealed when an enemy moves next to it.\"\n"
        "    affect_self=yes\n"
        "    [filter]\n"
        "        [filter_location]\n"
        "            [or]\n"
        "                terrain=*^F*\n"
        "            [/or]\n"
        "            [or]\n"
        "                time_of_day=chaotic\n"
        "            [/or]\n"
        "        [/filter_location]\n"
        "        [not]\n"
        "            [filter_location]\n"
        "                radius=2\n"
        "                [filter]\n"
        "                    ability=sw_ability_keen_senses\n"
        "                [/filter]\n"
        "            [/filter_location]\n"
        "        [/not]\n"
        "    [/filter]\n"
        "[/hides]"
    )


def cloaked() -> str:
    # Engine concealment for the sensor system (lua/sw_ew.lua): hidden only
    # while sw_ew sets the custom status sw_ew_concealed, i.e. while no enemy
    # team has identified the unit by sensors, intelligence or contact.
    return (
        "[hides]\n"
        "    id=sw_ability_cloaked\n"
        "    name= _ \"cloaked\"\n"
        "    description= _ \"A cloaking field hides this unit until an enemy team identifies it (sensor sweeps, close sensors or physical contact) or it fires. Partial sensor contacts are shown to the enemy as markers.\"\n"
        "    affect_self=yes\n"
        "    [filter]\n"
        "        status=sw_ew_concealed\n"
        "    [/filter]\n"
        "[/hides]"
    )


def tactical_genius() -> str:
    return (
        "[dummy]\n"
        "    id=sw_ability_tactical_genius\n"
        "    name= _ \"tactical genius\"\n"
        "    description= _ \"The Grand Admiral studies his opponents' art and culture to anticipate their tactics. Scenario events may grant his forces foreknowledge.\"\n"
        "[/dummy]"
    )


# --- Force and overwatch configuration (lua/sw_force.lua, lua/sw_overwatch.lua)
# Force profiles: Force Points, regeneration per turn and known powers.
# Lore: Luke is a trained Jedi Knight; Mara (the Emperor's Hand) has Force
# skills but fights with a vibroblade here; Leia is still in training;
# C'baoth and his clone Luuke draw on the dark side.
FORCE_PROFILES = {
    "sw_hero_luke": (8, 2, "push,pull,speed,sense,mind_trick,deflection"),
    "sw_hero_xwing_luke": (6, 2, "sense"),
    "sw_hero_mara": (5, 1, "speed,sense,push"),
    "sw_hero_leia": (4, 1, "sense,push"),
    "sw_hero_cbaoth": (10, 3, "push,pull,choke,sense,mind_trick,deflection"),
    "sw_hero_luuke": (6, 2, "push,choke,speed,deflection"),
}
POWER_NAMES = {
    "push": "Force Push", "pull": "Force Pull", "speed": "Force Speed", "sense": "Force Sense",
    "mind_trick": "Mind Trick", "choke": "Force Choke", "deflection": "Blaster Deflection",
}
# Overwatch by weapon, in priority order: (range in hexes, reactions per
# turn, accuracy modifier). Torpedoes, bombs, ion cannons and Force
# lightning are not reaction weapons.
OVERWATCH_WEAPONS = {
    "eweb_repeater": (3, 2, 0), "twin_blaster_cannon": (2, 2, -10), "turbolasers": (3, 2, -20),
    "point_defense": (1, 2, 0), "blaster_rifle": (2, 1, -10), "sw_blaster_rifle": (2, 1, -10),
    "blaster_carbine": (2, 1, -10), "bike_blaster": (2, 1, -10), "laser_cannons": (2, 1, -10),
    "bowcaster": (2, 1, -10), "heavy_blaster_pistol": (1, 1, -10), "blaster_pistol": (1, 1, -10),
    "hold_out_blaster": (1, 1, -10), "stun_blaster": (1, 1, -10), "suppressed_blaster": (2, 1, -10),
}


def force_ability(unit_id: str) -> str | None:
    profile = FORCE_PROFILES.get(unit_id)
    if not profile:
        return None
    fp_max, regen, powers = profile
    names = ", ".join(POWER_NAMES[p] for p in powers.split(","))
    return (
        "[dummy]\n"
        "    id=sw_ability_force\n"
        f"    fp_max={fp_max}\n"
        f"    fp_regen={regen}\n"
        f"    powers={powers}\n"
        f"    name= _ \"the Force\"\n"
        f"    description= _ \"Force Points: {fp_max}, regaining {regen} each turn. Powers: {names}. "
        "Use them from the right-click menu (The Force…). Inside a ysalamiri field the Force is blocked: "
        "no powers, no deflection, no regeneration.\"\n"
        "[/dummy]"
    )


def overwatch_ability(attacks: list[dict]) -> str | None:
    names = [a["name"] for a in attacks if a["range"] == "ranged"]
    for weapon, (rng, reactions, accuracy) in OVERWATCH_WEAPONS.items():
        if weapon in names:
            return (
                "[dummy]\n"
                "    id=sw_ability_overwatch\n"
                f"    weapons={weapon}\n"
                f"    range={rng}\n"
                f"    reactions={reactions}\n"
                f"    accuracy={accuracy}\n"
                "    damage=100\n"
                "    name= _ \"overwatch\"\n"
                f"    description= _ \"Can hold overwatch (right-click menu), committing this turn's attack. Until its next "
                f"turn, it fires {reactions} reaction volley(s) at enemies that move within {rng} hex(es) in sight. "
                "Hidden units cannot be targeted; a moving unit that is fired on stops but keeps its remaining moves.\"\n"
                "[/dummy]"
            )
    return None


# Sensors and electronic warfare (lua/sw_ew.lua). Units without an entry use
# their class defaults (capital ship 5 sensors/7 hexes/signature 8,
# starfighter 3/5/3, vehicle 3/4/4, infantry 2/3/2, creature 3/3/2).
# Lore (Legends): Imperial Star Destroyers mount powerful jammers and sensor
# decoy drones; A-wings carry military jammers; astromech-equipped X-wings
# and New Republic capital ships run counter-jamming; Thrawn's mole miners
# read as mining equipment on sensors (Sluis Van); his cloaked asteroids
# (Coruscant, Bilbringi) defeat ordinary sensors; Karrde's Wild Karrde
# relies on sensor tricks; Noghri and commandos run silent; Y-wings fly
# recon sweeps with Longprobe-style sensor packages.
EW_PROFILES = {
    "sw_unit_ob_cloaked_asteroid": dict(cloak=6, signature=1, sensor=0, sensor_range=0, **{"class": "object"}),
    "sw_unit_im_star_destroyer": dict(sensor=6, sensor_range=8, ecm=2, ecm_range=3, scan=3, decoys=1),
    "sw_unit_nr_docked_warship": dict(sensor=5, sensor_range=7, eccm=2, scan=3),
    "sw_unit_ob_dreadnaught": dict(sensor=4, sensor_range=6, signature=9),
    "sw_unit_im_minelayer": dict(scan=2),
    "sw_unit_nr_awing": dict(ecm=2, ecm_range=2),
    "sw_unit_nr_xwing": dict(eccm=1),
    "sw_unit_nr_ywing": dict(scan=3),   # Longprobe-style recon sensor package
    "sw_hero_xwing_luke": dict(eccm=1),
    "sw_hero_wedge": dict(eccm=1),
    "sw_unit_im_tie_interceptor": dict(sensor=4),
    "sw_unit_im_mole_miner": dict(signature=2, disguise_class="object"),
    "sw_unit_im_scout_trooper": dict(sensor=3, sensor_range=5, scan=2),
    "sw_unit_wk_lookout": dict(sensor=4, sensor_range=5, scan=2),
    "sw_hero_karrde": dict(scan=2, ecm=1, ecm_range=2, decoys=2),
    "sw_unit_nr_commando": dict(signature=1),
    "sw_unit_bi_commando": dict(signature=1),
    "sw_unit_im_noghri": dict(signature=1),
    "sw_hero_khabarakh": dict(signature=1),
    "sw_unit_im_infiltrator": dict(signature=1),
    "sw_unit_ob_shield_generator": dict(sensor=0, sensor_range=0, signature=6, **{"class": "object"}),
    "sw_unit_ob_cloning_cylinder": dict(sensor=0, sensor_range=0, signature=4, **{"class": "object"}),
    "sw_unit_ob_shipyard_platform": dict(sensor=4, sensor_range=5, signature=8, **{"class": "object"}),
}
EW_CLASS_NAMES = {"object": "object", "capital": "capital ship"}


def ew_ability(unit_id: str) -> str | None:
    profile = EW_PROFILES.get(unit_id)
    if not profile:
        return None
    attrs = "".join(f"    {k}={v}\n" for k, v in profile.items())
    parts = []
    if profile.get("cloak"):
        parts.append(f"cloak {profile['cloak']} (drops after firing)")
    if profile.get("ecm"):
        parts.append(f"jammer {profile['ecm']} over {profile.get('ecm_range', 2)} hexes (it is loud: +2 signature)")
    if profile.get("eccm"):
        parts.append(f"counter-jamming {profile['eccm']}")
    if profile.get("scan"):
        parts.append(f"active sweep +{profile['scan']} (right-click menu)")
    if profile.get("decoys"):
        parts.append(f"{profile['decoys']} sensor decoy(s)")
    if profile.get("disguise_class"):
        parts.append(f"reads as {EW_CLASS_NAMES.get(profile['disguise_class'], profile['disguise_class'])} until identified")
    if "sensor" in profile and profile.get("sensor_range", 1) > 0:
        parts.append(f"sensors {profile['sensor']} out to {profile.get('sensor_range', '?')} hexes")
    if "signature" in profile:
        parts.append(f"signature {profile['signature']}")
    return (
        "[dummy]\n"
        "    id=sw_ability_ew\n"
        f"{attrs}"
        "    name= _ \"sensors & EW\"\n"
        f"    description= _ \"Sensors and electronic warfare: {'; '.join(parts)}. See the Field Manual: Sensors and cloaking.\"\n"
        "[/dummy]"
    )


# --- Rank insignia (lua/sw_rank.lua) and air support (lua/sw_air.lua) --------
# Rank insignia are drawn into the unit's sprite as it gains rank: each
# after-max-level advancement adds one, and promoted types start at rank I.
# Styles: New Republic gold chevrons; Imperial red-over-blue rank plaque (the
# Empire's tiled rank bars); independents brass studs; dark Jedi violet.
# Creatures and objects have no rank.
RANK_HEROES = {
    "sw_hero_luke": "republic", "sw_hero_xwing_luke": "republic", "sw_hero_leia": "republic",
    "sw_hero_han": "republic", "sw_hero_chewbacca": "republic", "sw_hero_lando": "republic",
    "sw_hero_wedge": "republic", "sw_hero_bel_iblis": "republic",
    "sw_hero_mara": "independent", "sw_hero_karrde": "independent",
    "sw_hero_pellaeon": "imperial", "sw_hero_thrawn": "imperial", "sw_hero_khabarakh": "imperial",
    "sw_hero_cbaoth": "darkside", "sw_hero_luuke": "darkside",
}
RANK_PREFIXES = (
    ("sw_unit_nr_", "republic"), ("sw_unit_wk_", "republic"), ("sw_unit_bi_", "republic"),
    ("sw_unit_im_", "imperial"), ("sw_unit_sm_", "independent"), ("sw_unit_wy_", "independent"),
)
# Promoted unit types begin at rank I (their base type has none).
RANK_BASE = {"sw_unit_nr_sergeant": 1, "sw_unit_im_stormtrooper_sergeant": 1, "sw_unit_sm_veteran": 1}


def rank_style(uid: str) -> str | None:
    if uid in RANK_HEROES:
        return RANK_HEROES[uid]
    for prefix, style in RANK_PREFIXES:
        if uid.startswith(prefix):
            return style
    return None


# Forward observers can call off-map air sorties (range in hexes). Lore:
# New Republic sergeants and commandos, Imperial officers, stormtrooper
# sergeants and scout troopers, and commanders Han Solo, Lando Calrissian,
# Leia Organa Solo, Garm Bel Iblis and Captain Pellaeon.
FORWARD_OBSERVERS = {
    "sw_unit_nr_sergeant": 6, "sw_unit_nr_commando": 7, "sw_unit_bi_commando": 7,
    "sw_unit_im_officer": 6, "sw_unit_im_stormtrooper_sergeant": 5, "sw_unit_im_scout_trooper": 7,
    "sw_hero_han": 6, "sw_hero_lando": 6, "sw_hero_leia": 6, "sw_hero_bel_iblis": 7, "sw_hero_pellaeon": 6,
}
# Anti-air: (radius, accuracy penalty) against sorties striking near the unit.
ANTI_AIR = {
    "sw_unit_im_at_st": (2, 20), "sw_unit_nr_eweb_team": (2, 20),
}


def observer_ability(uid: str) -> str | None:
    rng = FORWARD_OBSERVERS.get(uid)
    if not rng:
        return None
    return (
        "[dummy]\n"
        "    id=sw_ability_forward_observer\n"
        f"    range={rng}\n"
        "    name= _ \"forward observer\"\n"
        f"    description= _ \"Can call the side's air sorties (right-click a hex within {rng} hexes that your side can see or "
        "track on sensors, then Call air support). Calling uses this unit's attack. Strafing runs hit a line of hexes at once; "
        "bombing runs hit an area at the start of your next turn. Sorties never finish off a unit.\"\n"
        "[/dummy]"
    )


def anti_air_ability(uid: str) -> str | None:
    aa = ANTI_AIR.get(uid)
    if not aa:
        return None
    radius, penalty = aa
    return (
        "[dummy]\n"
        "    id=sw_ability_anti_air\n"
        f"    radius={radius}\n"
        f"    penalty={penalty}\n"
        "    name= _ \"anti-air\"\n"
        f"    description= _ \"Fires on enemy air sorties striking within {radius} hexes: each such unit lowers the "
        f"sortie's accuracy by {penalty}% (up to 40% in all).\"\n"
        "[/dummy]"
    )


# Off-map sorties are shown by a fake unit flying over the ground map. The
# starfighter movement type cannot cross ground terrain, so craft that fly
# sorties get a hidden variation with flying movement for the animation only.
FLYOVER_CRAFT = {
    "sw_unit_nr_xwing", "sw_unit_nr_ywing", "sw_unit_nr_awing",
    "sw_unit_im_tie_fighter", "sw_unit_im_tie_interceptor", "sw_unit_im_tie_bomber",
}


def flyover_variation() -> str:
    return (
        "[variation]\n"
        "    variation_id=sw_flyover\n"
        "    variation_name= _ \"flyover\"\n"
        "    hide_help=yes\n"
        "    inherit=yes\n"
        "    movement_type=fly\n"
        "[/variation]"
    )


def rank_data_lua() -> str:
    lines = [
        "-- Generated by production/tools/gen_hte_units.py: do not edit.",
        "-- Rank insignia style and starting rank per unit type (lua/sw_rank.lua).",
        "return {",
    ]
    for u in ROSTER:
        style = rank_style(u["id"])
        if style:
            lines.append(f'\t{u["id"]} = {{ style = "{style}", base = {RANK_BASE.get(u["id"], 0)} }},')
    lines.append("}")
    return "\n".join(lines) + "\n"


ABILITY_BUILDERS = {
    "leadership": lambda: "{ABILITY_LEADERSHIP}",
    "heals4": lambda: "{ABILITY_HEALS}",
    "skirmisher": lambda: "{ABILITY_SKIRMISHER}",
    "ambush": lambda: "{ABILITY_AMBUSH}",
    "force_agility": force_agility,
    "force_healing": force_healing,
    "keen_senses": keen_senses,
    "noghri_stealth": noghri_stealth,
    "tactical_genius": tactical_genius,
    "cloaked": cloaked,
}

# Weapon specials. Values are WML snippets placed in [specials].
SPECIALS = {
    "firststrike": "{WEAPON_SPECIAL_FIRSTSTRIKE}",
    "marksman": "{WEAPON_SPECIAL_MARKSMAN}",
    "backstab": "{WEAPON_SPECIAL_BACKSTAB}",
    "slow": "{WEAPON_SPECIAL_SLOW}",
    "magical": "{WEAPON_SPECIAL_MAGICAL}",
    "deflection": (
        "[disable]\n"
        "    id=sw_special_deflection\n"
        "    name= _ \"deflection\"\n"
        "    description= _ \"A Jedi can turn blaster bolts back at the shooter but cannot start an attack this way. Deflection fails inside a ysalamiri bubble.\"\n"
        "    active_on=offense\n"
        "[/disable]\n"
        "[disable]\n"
        "    id=sw_special_deflection_ysalamiri\n"
        "    [filter_self]\n"
        "        [filter_location]\n"
        "            find_in=sw_ysalamiri_zone\n"
        "        [/filter_location]\n"
        "    [/filter_self]\n"
        "[/disable]"
    ),
    "force_hunter": (
        "[damage]\n"
        "    id=sw_special_force_hunter\n"
        "    name= _ \"Force hunter\"\n"
        "    description= _ \"Vornskrs sense the Force and attack Force-sensitive prey with extra ferocity: +50% damage against units with Force abilities.\"\n"
        "    multiply=1.5\n"
        "    [filter_opponent]\n"
        "        ability=sw_ability_force_agility\n"
        "    [/filter_opponent]\n"
        "[/damage]"
    ),
}


def attack(name, desc, kind, rng, dmg, num, icon=None, specials=(), max_range=None):
    return dict(name=name, desc=desc, type=kind, range=rng, damage=dmg, number=num, icon=icon,
                specials=list(specials), max_range=max_range)


# --- roster ---------------------------------------------------------------

def U(uid, name, desc, *, file, level, hp, mp, xp, cost, mt, attacks, alignment="neutral", race="human",
      usage="fighter", abilities=(), advances=None, gender=None, resist=None, hero=False, zoc=None,
      hide_help=False):
    return dict(id=uid, name=name, desc=desc, file=file, level=level, hp=hp, mp=mp, xp=xp, cost=cost, mt=mt,
                attacks=attacks, alignment=alignment, race=race, usage=usage, abilities=list(abilities),
                advances=advances, gender=gender, resist=resist or {}, hero=hero, zoc=zoc, hide_help=hide_help)


RIFLE = lambda d, n: attack("blaster_rifle", "blaster rifle", "fire", "ranged", d, n)
PISTOL = lambda d, n, sp=(): attack("blaster_pistol", "blaster pistol", "fire", "ranged", d, n, specials=sp)
BUTT = lambda d, n: attack("rifle_butt", "rifle butt", "impact", "melee", d, n)
FISTS = lambda d, n: attack("fists", "fists", "impact", "melee", d, n)
LASERS = lambda d, n, sp=(): attack("laser_cannons", "laser cannons", "fire", "ranged", d, n, specials=sp)

ROSTER = [
    # New Republic ---------------------------------------------------------
    U("sw_unit_nr_trooper", "New Republic Trooper",
      "The backbone of the New Republic Army: volunteers from a hundred worlds, many of them veterans of the Rebellion, armed with reliable blaster rifles.",
      file="hte_new_republic", level=1, hp=38, mp=5, xp=40, cost=14, mt="sw_infantry",
      attacks=[BUTT(5, 2), RIFLE(7, 3)], advances="sw_unit_nr_sergeant"),
    U("sw_unit_nr_sergeant", "New Republic Sergeant",
      "Sergeants hold New Republic squads together under fire. Their calm example steadies nearby troopers.",
      file="hte_new_republic", level=2, hp=50, mp=5, xp=90, cost=26, mt="sw_infantry",
      attacks=[BUTT(7, 2), RIFLE(9, 3)], abilities=["leadership"]),
    U("sw_unit_nr_commando", "New Republic Commando",
      "Lightly equipped specialists trained to slip between enemy positions, strike, and vanish before a response can form.",
      file="hte_new_republic", level=1, hp=34, mp=6, xp=42, cost=17, mt="sw_infantry", usage="scout",
      attacks=[attack("vibroknife", "vibroknife", "blade", "melee", 6, 3),
               attack("blaster_carbine", "blaster carbine", "fire", "ranged", 6, 3)],
      abilities=["skirmisher"]),
    U("sw_unit_nr_eweb_team", "E-Web Heavy Weapons Team",
      "A two-person crew with a tripod-mounted heavy repeating blaster. Slow to redeploy, but its fire reaches two hexes and shreds anything caught in the open.",
      file="hte_new_republic", level=1, hp=36, mp=4, xp=44, cost=19, mt="sw_infantry", usage="archer",
      attacks=[FISTS(4, 2),
               attack("eweb_repeater", "E-Web repeating blaster", "fire", "ranged", 10, 3, max_range=2)]),
    U("sw_unit_nr_field_medic", "Field Medic",
      "New Republic medics carry bacta patches and stim kits into the thick of the fighting to keep soldiers on their feet.",
      file="hte_new_republic", level=1, hp=30, mp=5, xp=40, cost=16, mt="sw_infantry", usage="healer",
      attacks=[PISTOL(5, 2)], abilities=["heals4"]),
    U("sw_unit_nr_militia", "Planetary Militia",
      "Local defense volunteers with little training and older weapons, fighting for their own homes.",
      file="hte_new_republic", level=0, hp=26, mp=5, xp=20, cost=8, mt="sw_infantry",
      attacks=[FISTS(4, 2), PISTOL(5, 2)], advances="sw_unit_nr_trooper"),
    U("sw_unit_wk_warrior", "Wookiee Warrior",
      "Wookiee warriors defend Kashyyyk's great wroshyr trees with ryyk blades and powerful bowcasters.",
      file="hte_new_republic", level=1, hp=48, mp=5, xp=44, cost=18, mt="sw_wookiee", race="sw_wookiee",
      attacks=[attack("ryyk_blade", "ryyk blade", "blade", "melee", 8, 3),
               attack("bowcaster", "bowcaster", "pierce", "ranged", 10, 2)]),
    U("sw_unit_wk_lookout", "Wookiee Lookout",
      "Lookouts keep watch from the high branches. Few intruders escape their senses, even Noghri.",
      file="hte_new_republic", level=1, hp=38, mp=6, xp=40, cost=15, mt="sw_wookiee", race="sw_wookiee",
      usage="archer",
      attacks=[attack("ryyk_blade", "ryyk blade", "blade", "melee", 5, 2),
               attack("bowcaster", "bowcaster", "pierce", "ranged", 8, 2)],
      abilities=["keen_senses"]),
    U("sw_unit_nr_xwing", "X-wing Starfighter",
      "The New Republic's workhorse starfighter: four laser cannons, proton torpedoes, shields, and a hyperdrive.",
      file="hte_space", level=1, hp=34, mp=8, xp=44, cost=20, mt="sw_starfighter", race="mechanical",
      usage="mixed fighter",
      attacks=[LASERS(8, 3), attack("proton_torpedoes", "proton torpedoes", "impact", "ranged", 16, 1,
                                    specials=["marksman"])]),
    U("sw_unit_nr_awing", "A-wing Interceptor",
      "Small, very fast interceptors built to catch enemy fighters and bombers before they reach their targets.",
      file="hte_space", level=1, hp=26, mp=10, xp=40, cost=18, mt="sw_starfighter", race="mechanical",
      usage="scout", attacks=[LASERS(7, 3, sp=["firststrike"])]),
    U("sw_unit_nr_ywing", "Y-wing Bomber",
      "Rugged, slow assault bombers whose ion cannons can disable a target's systems.",
      file="hte_space", level=1, hp=40, mp=7, xp=44, cost=22, mt="sw_starfighter", race="mechanical",
      usage="mixed fighter",
      attacks=[LASERS(6, 2),
               attack("ion_cannon", "ion cannon", "cold", "ranged", 7, 2, specials=["slow"]),
               attack("proton_torpedoes", "proton torpedoes", "impact", "ranged", 16, 2)]),
    U("sw_unit_nr_docked_warship", "Docked Warship",
      "A New Republic warship tied up at the shipyards for refit, with only a skeleton crew aboard: it cannot move or fight back, and must be defended.",
      file="hte_space", level=2, hp=120, mp=0, xp=100, cost=0, mt="sw_capital", race="mechanical",
      attacks=[], zoc="no"),

    # Heroes ---------------------------------------------------------------
    U("sw_hero_luke", "Jedi Knight",
      "Luke Skywalker, the last fully trained Jedi Knight in the galaxy, carries the lightsaber he built himself. His Force abilities fail inside a ysalamiri bubble.",
      file="hte_heroes", level=3, hp=52, mp=6, xp=150, cost=60, mt="sw_jedi", hero=True, gender="male",
      attacks=[attack("lightsaber", "lightsaber", "arcane", "melee", 11, 4),
               attack("deflection", "deflected bolts", "fire", "ranged", 7, 2, specials=["deflection"])],
      abilities=["force_agility", "force_healing"]),
    U("sw_hero_xwing_luke", "X-wing Pilot (Jedi)",
      "Luke Skywalker at the controls of his X-wing, with his astromech droid riding behind the cockpit.",
      file="hte_heroes", level=3, hp=50, mp=8, xp=150, cost=60, mt="sw_starfighter", race="mechanical",
      hero=True, gender="male",
      attacks=[LASERS(9, 4), attack("proton_torpedoes", "proton torpedoes", "impact", "ranged", 18, 2,
                                    specials=["marksman"])]),
    U("sw_hero_leia", "Chief of State",
      "Leia Organa Solo, a leader of the New Republic, a veteran of the Rebellion, and Force-sensitive herself. The Noghri want her alive.",
      file="hte_heroes", level=2, hp=40, mp=5, xp=100, cost=40, mt="sw_jedi", hero=True, gender="female",
      attacks=[FISTS(5, 2), PISTOL(7, 3)], abilities=["leadership"]),
    U("sw_hero_han", "Smuggler General",
      "Han Solo, captain of the Millennium Falcon and a general of the New Republic, is quicker on the draw than anyone he has met.",
      file="hte_heroes", level=2, hp=46, mp=6, xp=100, cost=40, mt="sw_infantry", hero=True, gender="male",
      attacks=[FISTS(6, 2), attack("heavy_blaster_pistol", "heavy blaster pistol", "fire", "ranged", 9, 3,
                                   specials=["firststrike"])]),
    U("sw_hero_chewbacca", "Wookiee Copilot",
      "Chewbacca, Han Solo's Wookiee partner and copilot, has sworn a life debt and defends his friends with ferocious strength.",
      file="hte_heroes", level=2, hp=62, mp=5, xp=100, cost=40, mt="sw_wookiee", race="sw_wookiee", hero=True,
      gender="male",
      attacks=[attack("wookiee_strength", "Wookiee strength", "impact", "melee", 10, 3),
               attack("bowcaster", "bowcaster", "pierce", "ranged", 13, 2)]),
    U("sw_hero_lando", "Baron Administrator",
      "Lando Calrissian, gambler, general, and businessman, runs the mobile mining city on Nkllon and still enjoys long odds.",
      file="hte_heroes", level=2, hp=42, mp=6, xp=100, cost=40, mt="sw_infantry", hero=True, gender="male",
      attacks=[FISTS(5, 2), PISTOL(7, 3)], abilities=["leadership"]),
    U("sw_hero_mara", "Karrde's Second",
      "Mara Jade, Talon Karrde's second-in-command, is a superb pilot and fighter. She has unexplained reasons to want Luke Skywalker dead.",
      file="hte_heroes", level=2, hp=42, mp=6, xp=100, cost=40, mt="sw_jedi", hero=True, gender="female",
      attacks=[attack("vibroblade", "vibroblade", "blade", "melee", 8, 3),
               attack("hold_out_blaster", "hold-out blaster", "fire", "ranged", 8, 3, specials=["marksman"])],
      abilities=["ambush"]),
    U("sw_hero_karrde", "Smuggler Chief",
      "Talon Karrde leads the galaxy's most capable smuggling organization and values information and neutrality above everything else.",
      file="hte_heroes", level=2, hp=40, mp=5, xp=100, cost=40, mt="sw_infantry", hero=True, gender="male",
      attacks=[FISTS(5, 2), PISTOL(8, 2, sp=["marksman"])], abilities=["leadership"]),
    U("sw_hero_wedge", "Rogue Leader",
      "Wedge Antilles, commander of Rogue Squadron, is one of the finest starfighter pilots in the New Republic.",
      file="hte_heroes", level=3, hp=48, mp=8, xp=150, cost=60, mt="sw_starfighter", race="mechanical",
      hero=True, gender="male",
      attacks=[LASERS(9, 4), attack("proton_torpedoes", "proton torpedoes", "impact", "ranged", 16, 2,
                                    specials=["marksman"])],
      abilities=["leadership"]),
    U("sw_hero_pellaeon", "Imperial Captain",
      "Captain Gilad Pellaeon commands the Star Destroyer Chimaera. A career officer, he has come to trust the Grand Admiral completely.",
      file="hte_heroes", level=3, hp=50, mp=5, xp=150, cost=50, mt="sw_infantry", hero=True, gender="male",
      attacks=[FISTS(6, 2), PISTOL(8, 3)], abilities=["leadership"]),
    U("sw_hero_thrawn", "Grand Admiral",
      "Grand Admiral Thrawn, the only alien to reach the Empire's highest rank, has returned from the Unknown Regions to lead the Imperial Remnant.",
      file="hte_heroes", level=4, hp=60, mp=5, xp=200, cost=80, mt="sw_infantry", hero=True, gender="male",
      attacks=[FISTS(7, 2), PISTOL(10, 3)], abilities=["leadership", "tactical_genius"]),

    # Imperial Remnant -----------------------------------------------------
    U("sw_unit_im_stormtrooper", "Stormtrooper",
      "The Empire's armored infantry. Their plastoid armor turns blades and glancing bolts, and their discipline has survived the Emperor's death.",
      file="hte_imperial", level=1, hp=36, mp=5, xp=40, cost=14, mt="sw_armored_trooper",
      attacks=[BUTT(5, 2), RIFLE(7, 3)], advances="sw_unit_im_stormtrooper_sergeant"),
    U("sw_unit_im_stormtrooper_sergeant", "Stormtrooper Sergeant",
      "Squad leaders marked by their pauldrons, who drive their troopers forward with harsh efficiency.",
      file="hte_imperial", level=2, hp=48, mp=5, xp=90, cost=27, mt="sw_armored_trooper",
      attacks=[BUTT(7, 2), RIFLE(9, 3)], abilities=["leadership"]),
    U("sw_unit_im_scout_trooper", "Scout Trooper",
      "Lightly armored scouts on speeder bikes: very fast in the open, dangerous among trees.",
      file="hte_imperial", level=1, hp=32, mp=8, xp=40, cost=17, mt="sw_repulsor", usage="scout",
      attacks=[attack("ram", "ram", "impact", "melee", 7, 2),
               attack("bike_blaster", "bike blaster cannon", "fire", "ranged", 6, 3)]),
    U("sw_unit_im_officer", "Imperial Officer",
      "Field officers of the Imperial Remnant, trained to coordinate infantry, walkers, and air support.",
      file="hte_imperial", level=2, hp=40, mp=5, xp=90, cost=30, mt="sw_infantry",
      attacks=[FISTS(5, 2), PISTOL(7, 2)], abilities=["leadership"]),
    U("sw_unit_im_at_st", "AT-ST Walker",
      "All Terrain Scout Transports: two-legged walkers with chin-mounted blaster cannons and a grenade launcher. Weak to ion fire and lightsabers.",
      file="hte_imperial", level=2, hp=64, mp=4, xp=90, cost=34, mt="sw_walker", race="mechanical",
      usage="archer",
      attacks=[attack("stomp", "stomp", "impact", "melee", 9, 2),
               attack("twin_blaster_cannon", "twin blaster cannon", "fire", "ranged", 10, 3),
               attack("concussion_grenade", "concussion grenade launcher", "impact", "ranged", 14, 1)]),
    U("sw_unit_im_noghri", "Noghri Commando",
      "Silent Noghri killers who move unseen through forest and darkness. They serve the Grand Admiral without question.",
      file="hte_imperial", level=2, hp=40, mp=6, xp=90, cost=30, mt="sw_noghri", race="sw_noghri",
      alignment="chaotic",
      attacks=[attack("noghri_knives", "Noghri knives", "blade", "melee", 9, 4, specials=["backstab"]),
               attack("stun_blaster", "stun blaster", "fire", "ranged", 5, 2)],
      abilities=["noghri_stealth"]),
    U("sw_unit_im_tie_fighter", "TIE Fighter",
      "Mass-produced, unshielded short-range fighters. They are fast and numerous and do not last long once hit.",
      file="hte_space", level=1, hp=24, mp=9, xp=36, cost=12, mt="sw_starfighter", race="mechanical",
      usage="scout", attacks=[LASERS(7, 3)]),
    U("sw_unit_im_tie_interceptor", "TIE Interceptor",
      "A faster, more heavily armed TIE design flown by the Remnant's best pilots.",
      file="hte_space", level=2, hp=30, mp=10, xp=80, cost=24, mt="sw_starfighter", race="mechanical",
      attacks=[LASERS(9, 4, sp=["firststrike"])]),
    U("sw_unit_im_tie_bomber", "TIE Bomber",
      "Double-hulled TIE bombers carry concussion bombs for stations and capital ships.",
      file="hte_space", level=1, hp=34, mp=7, xp=40, cost=18, mt="sw_starfighter", race="mechanical",
      usage="mixed fighter",
      attacks=[LASERS(5, 2), attack("concussion_bombs", "concussion bombs", "impact", "ranged", 16, 2)]),
    U("sw_unit_im_mole_miner", "Hijacked Mole Miner",
      "A stolen asteroid-mining craft with plasma jets that can cut through hull plating. Imperial crews use them to board ships.",
      file="hte_space", level=1, hp=44, mp=4, xp=40, cost=20, mt="sw_starfighter", race="mechanical",
      attacks=[attack("plasma_jets", "plasma jets", "fire", "melee", 10, 2)]),
    U("sw_unit_im_star_destroyer", "Imperial Star Destroyer",
      "A wedge-shaped capital ship sixteen hundred meters long, bristling with turbolasers and ion cannons.",
      file="hte_space", level=4, hp=220, mp=2, xp=200, cost=0, mt="sw_capital", race="mechanical",
      attacks=[attack("turbolasers", "turbolasers", "fire", "ranged", 20, 3),
               attack("ion_cannons", "ion cannons", "cold", "ranged", 12, 2, specials=["slow"])]),

    # Campaign II (Dark Force Rising) -------------------------------------
    U("sw_hero_khabarakh", "Noghri Commando",
      "Khabarakh of the clan Kihm'bar, a Noghri commando who has begun to doubt the Empire his people serve.",
      file="dfr_units", level=2, hp=42, mp=6, xp=100, cost=40, mt="sw_noghri", race="sw_noghri", hero=True,
      gender="male", alignment="chaotic",
      attacks=[attack("noghri_knives", "Noghri knives", "blade", "melee", 9, 4, specials=["backstab"]),
               attack("stun_blaster", "stun blaster", "fire", "ranged", 6, 2)],
      abilities=["noghri_stealth"]),
    U("sw_hero_cbaoth", "Jedi Master",
      "Joruus C'baoth claims to be a Jedi Master of the Old Republic. His power is immense; his judgment is not. His Force abilities fail inside a ysalamiri bubble.",
      file="dfr_units", level=4, hp=60, mp=5, xp=200, cost=80, mt="sw_jedi", hero=True, gender="male",
      attacks=[attack("lightsaber", "lightsaber", "arcane", "melee", 12, 4),
               attack("force_lightning", "Force lightning", "fire", "ranged", 12, 3, specials=["magical"])],
      abilities=["force_agility", "force_healing"]),
    U("sw_hero_bel_iblis", "Senator-General",
      "Garm Bel Iblis, a founder of the Rebellion who broke with its leaders and fought on alone with his own private army.",
      file="dfr_units", level=3, hp=48, mp=5, xp=150, cost=50, mt="sw_infantry", hero=True, gender="male",
      attacks=[FISTS(6, 2), PISTOL(9, 3, sp=["marksman"])], abilities=["leadership"]),
    U("sw_unit_bi_commando", "Corellian Commando",
      "Veterans of Bel Iblis's private army: disciplined, well equipped, and fiercely loyal to their Senator.",
      file="dfr_units", level=1, hp=40, mp=5, xp=44, cost=17, mt="sw_infantry",
      attacks=[BUTT(6, 2), RIFLE(8, 3)]),
    U("sw_unit_im_clone_trooper", "Clone Stormtrooper",
      "Soldiers grown in the Grand Admiral's new cloning cylinders and sealed inside stormtrooper armor. They fight without hesitation.",
      file="dfr_units", level=1, hp=40, mp=5, xp=40, cost=16, mt="sw_armored_trooper",
      attacks=[BUTT(6, 2), RIFLE(8, 3)], advances="sw_unit_im_stormtrooper_sergeant"),
    U("sw_unit_im_decon_droid", "Decontamination Droid",
      "Slow, heavily built droids that have worked Honoghr's poisoned soil for a generation.",
      file="dfr_units", level=1, hp=50, mp=3, xp=40, cost=15, mt="sw_walker", race="mechanical",
      attacks=[attack("sprayer", "chemical sprayer", "cold", "ranged", 6, 2, specials=["slow"]),
               attack("manipulator", "manipulator arm", "impact", "melee", 8, 2)]),
    U("sw_unit_ob_dreadnaught", "Katana Dreadnaught",
      "One of two hundred heavy cruisers lost before the Clone Wars, its systems slaved together and its crews long dead.",
      file="dfr_units", level=3, hp=160, mp=1, xp=150, cost=0, mt="sw_capital", race="mechanical",
      attacks=[attack("turbolasers", "turbolasers", "fire", "ranged", 14, 3)], zoc="no"),
    U("sw_unit_nr_boarding_shuttle", "Boarding Shuttle",
      "An armored shuttle carrying a boarding crew. It secures a derelict ship by docking beside it.",
      file="dfr_units", level=1, hp=40, mp=6, xp=40, cost=20, mt="sw_starfighter", race="mechanical",
      attacks=[LASERS(5, 2)]),
    U("sw_unit_im_boarding_shuttle", "Imperial Assault Shuttle",
      "An Imperial boarding craft packed with clone stormtroopers.",
      file="dfr_units", level=1, hp=44, mp=6, xp=40, cost=20, mt="sw_starfighter", race="mechanical",
      attacks=[LASERS(6, 2)]),

    # Campaign III (The Last Command) -------------------------------------
    U("sw_hero_luuke", "Dark Clone",
      "Luuke, a clone grown from Luke Skywalker's hand and raised by Joruus C'baoth as the apprentice Luke refused to be. His Force abilities fail inside a ysalamiri bubble.",
      file="tlc_units", level=4, hp=56, mp=6, xp=200, cost=80, mt="sw_jedi", hero=True, gender="male",
      attacks=[attack("lightsaber", "lightsaber", "arcane", "melee", 11, 4),
               attack("force_lightning", "Force lightning", "fire", "ranged", 10, 3, specials=["magical"])],
      abilities=["force_agility"]),
    U("sw_unit_wy_myneyrshi", "Myneyrshi Warrior",
      "Four-armed Wayland hunters who fight with long spears and short bows at once.",
      file="tlc_units", level=1, hp=38, mp=6, xp=42, cost=15, mt="sw_wookiee", race="sw_myneyrshi",
      attacks=[attack("spear", "spear", "pierce", "melee", 7, 3, specials=["firststrike"]),
               attack("bow", "bow", "pierce", "ranged", 6, 3)]),
    U("sw_unit_wy_psadan", "Psadan Elder",
      "Slow, armored Psadans who wade into a fight and do not leave it.",
      file="tlc_units", level=1, hp=52, mp=4, xp=44, cost=17, mt="sw_armored_trooper", race="sw_psadan",
      attacks=[attack("war_club", "war club", "impact", "melee", 11, 2)]),
    U("sw_unit_im_royal_guard", "Imperial Guard",
      "Crimson-robed elite guards who once served the Emperor and still hold his storehouse at Mount Tantiss.",
      file="tlc_units", level=2, hp=46, mp=5, xp=90, cost=30, mt="sw_infantry",
      attacks=[attack("force_pike", "force pike", "blade", "melee", 10, 3, specials=["firststrike"]),
               PISTOL(6, 2)]),
    U("sw_unit_im_infiltrator", "Imperial Infiltrator",
      "Commandos trained to move unseen through cities and palaces.",
      file="tlc_units", level=1, hp=32, mp=6, xp=40, cost=18, mt="sw_noghri",
      attacks=[attack("vibroknife", "vibroknife", "blade", "melee", 7, 3, specials=["backstab"]), PISTOL(6, 2)],
      abilities=["ambush"]),
    U("sw_unit_im_minelayer", "Imperial Minelayer",
      "A converted bulk freighter that releases cloaked asteroids into planetary orbit.",
      file="tlc_units", level=2, hp=90, mp=4, xp=90, cost=0, mt="sw_capital", race="mechanical",
      attacks=[LASERS(8, 2)]),
    U("sw_unit_ob_cloaked_asteroid", "Cloaked Asteroid",
      "A rock in orbit, hidden by a stealth field. Ships that stray next to one are damaged.",
      file="tlc_units", level=0, hp=30, mp=0, xp=20, cost=0, mt="sw_capital", race="mechanical",
      attacks=[], abilities=["cloaked"], zoc="no"),
    U("sw_unit_ob_shield_generator", "Shield Generator",
      "A planetary shield generator protecting the mountain's entrance.",
      file="tlc_units", level=1, hp=80, mp=0, xp=40, cost=0, mt="sw_capital", race="mechanical",
      attacks=[], zoc="no"),
    U("sw_unit_ob_cloning_cylinder", "Cloning Cylinder",
      "One of the Emperor's Spaarti cloning cylinders, now growing soldiers for the Grand Admiral.",
      file="tlc_units", level=0, hp=30, mp=0, xp=20, cost=0, mt="sw_capital", race="mechanical",
      attacks=[], zoc="no"),
    U("sw_unit_ob_shipyard_platform", "Shipyard Platform",
      "An orbital construction platform at the Bilbringi shipyards. It has no weapons of its own; the fleet defends it.",
      file="tlc_units", level=2, hp=110, mp=0, xp=90, cost=0, mt="sw_capital", race="mechanical",
      attacks=[], zoc="no"),

    # Smugglers and wildlife ----------------------------------------------
    U("sw_unit_sm_smuggler", "Smuggler",
      "Members of Talon Karrde's organization: pilots, slicers, and gunhands, loyal to Karrde before any government.",
      file="hte_smugglers", level=1, hp=34, mp=6, xp=40, cost=13, mt="sw_infantry",
      attacks=[attack("vibroknife", "vibroknife", "blade", "melee", 5, 3), PISTOL(7, 2)],
      advances="sw_unit_sm_veteran"),
    U("sw_unit_sm_veteran", "Smuggler Veteran",
      "Hardened fringe fighters who make every shot count.",
      file="hte_smugglers", level=2, hp=44, mp=6, xp=90, cost=26, mt="sw_infantry",
      attacks=[attack("vibroknife", "vibroknife", "blade", "melee", 7, 3), PISTOL(9, 3, sp=["marksman"])]),
    U("sw_unit_wl_vornskr", "Vornskr",
      "Whip-tailed Myrkr predators that hunt by sensing the Force and attack Force-sensitives on sight.",
      file="hte_smugglers", level=1, hp=30, mp=7, xp=40, cost=12, mt="sw_beast", race="sw_vornskr",
      alignment="chaotic",
      attacks=[attack("fangs", "fangs", "blade", "melee", 6, 3, specials=["force_hunter"]),
               attack("whip_tail", "whip tail", "impact", "melee", 4, 2)]),
]

FILES = {
    "hte_new_republic": "New Republic and allied ground units for Campaign I.",
    "hte_space": "Starfighters, capital ships, and space set pieces for Campaign I.",
    "hte_heroes": "Named characters for Campaign I. Instances set random_traits=no.",
    "hte_imperial": "Imperial Remnant ground forces for Campaign I.",
    "hte_smugglers": "Karrde's smugglers and Myrkr wildlife for Campaign I.",
    "dfr_units": "Characters, forces, and craft introduced in Campaign II (Dark Force Rising).",
    "tlc_units": "Characters, natives, forces, and structures introduced in Campaign III (The Last Command).",
}


def slug(unit_id: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", unit_id.casefold()).strip("-")


def frame(image: str, duration: int) -> str:
    return f"[frame]\n    image={image}\n    duration={duration}\n[/frame]"


def animations(u: dict) -> str:
    s = slug(u["id"])
    base = f"units/{s}"
    has_melee = any(a["range"] == "melee" for a in u["attacks"])
    has_ranged = any(a["range"] == "ranged" for a in u["attacks"])
    blocks = [
        "[standing_anim]\n" + indent(frame(f"{base}/standing.png", 1000), 4) + "\n[/standing_anim]",
        "[idle_anim]\n" + indent(frame(f"{base}/idle-1.png", 300), 4) + "\n"
        + indent(frame(f"{base}/idle-2.png", 300), 4) + "\n[/idle_anim]",
        "[movement_anim]\n" + indent(with_sound(frame(f"{base}/move-1.png", 150),
                                                None if u["id"] in STATIONARY else MOVE_SOUNDS.get(u["mt"])), 4) + "\n"
        + indent(frame(f"{base}/move-2.png", 150), 4) + "\n[/movement_anim]",
    ]
    static = STATIC_ANIMS.get(u["id"])
    if static is not None:
        keep = [blocks[0]] + ([blocks[1]] if "idle" in static else [])
        if "defend" in static:
            keep.append("[defend]\n" + indent(frame(f"{base}/defend.png", 250), 4) + "\n[/defend]")
        keep.append(
            "[death]\n" + indent(with_sound(frame(f"{base}/death-1.png", 200),
                                            DEATH_OVERRIDES.get(u["id"], DEATH_SOUNDS.get(u["mt"]))), 4) + "\n"
            + indent(frame(f"{base}/death-2.png", 400), 4) + "\n[/death]")
        return "\n".join(keep)
    # The melee and ranged frames are always wired so the art contract stays
    # complete; the range filter keeps an absent attack range from using them.
    melee = [a for a in expanded_attacks(u) if a["range"] == "melee"]
    for a in melee or [None]:
        blocks.append(melee_anim(base, u["id"], a))
    ranged = [a for a in expanded_attacks(u) if a["range"] == "ranged"]
    # One animation per ranged attack, each firing its own projectile. A unit
    # without a ranged attack keeps one plain ranged block so its art set is
    # still fully referenced.
    for a in ranged or [None]:
        blocks.append(ranged_anim(base, u["id"], a))
    del has_melee, has_ranged
    blocks.append("[defend]\n" + indent(frame(f"{base}/defend.png", 250), 4) + "\n[/defend]")
    blocks.append(
        "[death]\n" + indent(with_sound(frame(f"{base}/death-1.png", 200),
                                        DEATH_OVERRIDES.get(u["id"], DEATH_SOUNDS.get(u["mt"]))), 4) + "\n"
        + indent(frame(f"{base}/death-2.png", 400), 4) + "\n[/death]"
    )
    return "\n".join(blocks)


# --- projectiles ---------------------------------------------------------------
# Owner rule (2026-10-02): Imperial or evil units fire red, New Republic units
# green or blue, neutral units orange or green -- unless film or Legends lore
# fixes the colour. Lore overrides used here:
#   * TIE starfighters and Imperial Star Destroyer turbolasers fire green.
#   * X-wing, Y-wing and A-wing laser cannons fire red.
#   * Han Solo's heavy blaster pistol (DL-44) fires red.
#   * Luke's deflected bolts are the Imperial red bolts he turns back.
#   * Stun settings fire blue rings; ion cannons a pale blue discharge.
IMPERIAL_HEROES = {"sw_hero_thrawn", "sw_hero_pellaeon", "sw_hero_cbaoth", "sw_hero_luuke"}
NEUTRAL_HEROES = {"sw_hero_karrde", "sw_hero_mara"}
IMPERIAL_OBJECTIVES = {"sw_unit_ob_shipyard_platform", "sw_unit_ob_dreadnaught"}
NO_PROJECTILE = {"sprayer", "jamming_equipment"}
HEAVY_WEAPONS = {"turbolasers", "turbo_laser", "twin_blaster_cannon", "blaster_cannon", "eweb_repeater",
                 "heavy_laser_cannons", "heavy_blaster", "point_defense", "dual_laser_cannons"}
LORE_COLORS = {
    ("sw_hero_han", "heavy_blaster_pistol"): "red",
    ("sw_hero_luke", "deflection"): "red",
    ("sw_unit_im_star_destroyer", "turbolasers"): "green",
}
REPUBLIC_STARFIGHTERS = {"sw_unit_nr_xwing", "sw_unit_nr_ywing", "sw_unit_nr_awing", "sw_hero_xwing_luke",
                         "sw_hero_wedge"}


# Muzzle flashes (owner rule 2026-10-04): a ranged attack's laser colour
# matches the muzzle flash of the sprite that fires it. Measured from the art
# by production/tools/scan_muzzle_flashes.py:
#   painted  the flash is part of a hand-drawn firing frame; bolts take its colour.
#   derived  the sprite has no flash colour of its own; the faction/lore logic
#            below picks the bolt colour, and each attack's firing frame blits
#            a flash of that same colour at the muzzle point.
#   posed    hand-posed firing frames drawn without a flash: handled like
#            derived, with the flash blitted at the weapon tip.
MUZZLE_FLASHES_PATH = Path(__file__).resolve().parent / "muzzle_flashes.json"
MUZZLE_FLASHES: dict[str, dict] = (json.loads(MUZZLE_FLASHES_PATH.read_text(encoding="utf-8"))
                                   if MUZZLE_FLASHES_PATH.exists() else {})


def painted_flash(unit_id: str) -> str | None:
    entry = MUZZLE_FLASHES.get(slug(unit_id), {})
    return entry.get("color") if entry.get("kind") == "painted" else None


def flash_overlay(unit_id: str, attack_name: str, missile: tuple[str, str | None] | None) -> str:
    """Image-path suffix that draws this attack's muzzle flash on the firing
    frame, in the colour of its projectile; "" when none is drawn (no
    projectile, bows and bombs, or a hand-drawn flash already in the art)."""
    entry = MUZZLE_FLASHES.get(slug(unit_id))
    if not missile or not entry or entry.get("kind") not in ("derived", "posed"):
        return ""
    if attack_name == "bow" or attack_name.startswith("concussion_"):
        return ""
    image = missile[0]
    if "sw-ion" in image:
        color = "ion"
    elif "sw-force-lightning" in image:
        color = "lightning"
    elif "sw-torpedo" in image:
        color = "torpedo"
    elif "sw-stun" in image:
        color = "blue"
    else:
        found = re.search(r"sw-(?:heavy-)?bolt-([a-z]+)-n\.png", image)
        if not found:
            return ""
        color = found.group(1)
    x, y = entry["blit"]
    return f"~BLIT(projectiles/sw-flash-{color}.png,{x},{y})"


def faction_color(unit_id: str) -> str:
    if (unit_id.startswith(("sw_unit_im_", "sw_unit_irm_")) or unit_id in IMPERIAL_HEROES
            or unit_id in IMPERIAL_OBJECTIVES):
        return "red"
    if unit_id.startswith("sw_unit_sm_") or unit_id in NEUTRAL_HEROES:
        return "orange"
    if unit_id.startswith("sw_unit_wk_") or unit_id == "sw_hero_chewbacca":
        return "green"  # Wookiee bowcasters: allied to the New Republic
    return "blue"


def projectile(unit_id: str, attack_name: str) -> tuple[str, str | None] | None:
    """(image, diagonal image) fired by one ranged attack, or None."""
    if attack_name in NO_PROJECTILE:
        return None
    if attack_name == "bow":
        return "projectiles/missile-n.png", "projectiles/missile-ne.png"
    if attack_name.startswith("ion_"):
        return "projectiles/sw-ion-n.png", "projectiles/sw-ion-ne.png"
    if attack_name.startswith("proton_torpedo"):
        return "projectiles/sw-torpedo.png", None
    if attack_name.startswith("concussion_"):
        return "projectiles/sw-bomb-n.png", "projectiles/sw-bomb-ne.png"
    if attack_name == "force_lightning":
        return "projectiles/sw-force-lightning-n.png", "projectiles/sw-force-lightning-ne.png"
    if attack_name == "stun_blaster":
        return "projectiles/sw-stun-n.png", "projectiles/sw-stun-ne.png"
    # A flash painted into the sprite's own firing frame decides first.
    color = painted_flash(unit_id) or LORE_COLORS.get((unit_id, attack_name))
    if color is None and attack_name.endswith("laser_cannons"):
        if unit_id.startswith("sw_unit_im_tie_"):
            color = "green"
        elif unit_id in REPUBLIC_STARFIGHTERS:
            color = "red"
    color = color or faction_color(unit_id)
    kind = "sw-heavy-bolt" if attack_name in HEAVY_WEAPONS else "sw-bolt"
    return f"projectiles/{kind}-{color}-n.png", f"projectiles/{kind}-{color}-ne.png"


# --- sounds ------------------------------------------------------------------
# Original synthesized effects (production/tools/gen_sound_effects.py) for
# Star Wars weapons; mainline sounds only for natural attacks (fists, bites,
# clubs, the Wayland natives' spears and bows).
MELEE_SOUNDS = {
    "lightsaber": "sw-lightsaber.wav", "vibroblade": "sw-vibroblade.wav", "vibroknife": "sw-vibroblade.wav",
    "force_pike": "sw-vibroblade.wav", "ryyk_blade": "sword-1.ogg", "noghri_knives": "dagger-swish.wav",
    "fists": "fist.ogg", "wookiee_strength": "fist.ogg", "rifle_butt": "club.ogg", "stomp": "club.ogg",
    "ram": "club.ogg", "war_club": "club.ogg", "spear": "spear.ogg", "fangs": "bite.ogg",
    "whip_tail": "tail.ogg", "manipulator": "club.ogg", "plasma_jets": "sw-ion.wav",
}


# Hit and miss sounds at the moment of impact (core SOUND:HIT_AND_MISS).
RANGED_IMPACTS = {
    "sw-blaster.wav": ("sw-blaster-hit.wav", "sw-blaster-miss.wav"),
    "sw-blaster-heavy.wav": ("sw-heavy-hit.wav", "sw-heavy-miss.wav"),
    "sw-laser-cannon.wav": ("sw-laser-hit.wav", "sw-laser-miss.wav"),
    "sw-turbolaser.wav": ("sw-turbolaser-hit.wav", "sw-turbolaser-miss.wav"),
    "sw-ion.wav": ("sw-ion-hit.wav", "sw-ion-miss.wav"),
    "sw-torpedo.wav": ("sw-torpedo-hit.wav", "sw-torpedo-miss.wav"),
    "sw-stun.wav": ("sw-stun-hit.wav", "sw-stun-miss.wav"),
    "sw-bowcaster.wav": ("sw-bowcaster-hit.wav", "sw-bowcaster-miss.wav"),
    "sw-force-lightning.wav": ("sw-lightning-hit.wav", "sw-lightning-miss.wav"),
}
MELEE_IMPACTS = {
    "lightsaber": ("sw-saber-clash.wav", "sw-lightsaber.wav"),
    "vibroblade": ("sw-vibro-hit.wav", "sw-vibroblade.wav"),
    "vibroknife": ("sw-vibro-hit.wav", "sw-vibroblade.wav"),
    "force_pike": ("sw-vibro-hit.wav", "sw-vibroblade.wav"),
    "ryyk_blade": ("sword-1.ogg", "miss-1.ogg"),
    "noghri_knives": ("sword-1.ogg", "dagger-swish.wav"),
    "fists": ("fist.ogg", "miss-1.ogg"),
    "wookiee_strength": ("sw-wookiee-roar.wav", "miss-2.ogg"),
    "rifle_butt": ("club.ogg", "club-miss.ogg"),
    "stomp": ("club.ogg", "club-miss.ogg"),
    "ram": ("club.ogg", "club-miss.ogg"),
    "war_club": ("club.ogg", "club-miss.ogg"),
    "manipulator": ("club.ogg", "club-miss.ogg"),
    "spear": ("spear.ogg", "spear-miss.ogg"),
    "fangs": ("bite.ogg", "sw-vornskr-snarl.wav"),
    "whip_tail": ("tail.ogg", "miss-3.ogg"),
    "plasma_jets": ("sw-ion-hit.wav", "miss-1.ogg"),
}
# Death and movement sounds by movement type, with a few lore exceptions.
DEATH_SOUNDS = {
    "sw_armored_trooper": "sw-death-armor.wav", "sw_infantry": "sw-death-soft.wav", "sw_jedi": "sw-death-soft.wav",
    "sw_noghri": "sw-death-soft.wav", "sw_wookiee": "sw-death-wookiee.wav", "sw_beast": "sw-death-beast.wav",
    "sw_repulsor": "sw-death-vehicle.wav", "sw_walker": "sw-death-vehicle.wav",
    "sw_starfighter": "sw-death-fighter.wav", "sw_capital": "sw-death-capital.wav",
}
DEATH_OVERRIDES = {
    "sw_unit_wy_myneyrshi": "sw-death-soft.wav", "sw_unit_wy_psadan": "sw-death-soft.wav",
    "sw_unit_im_decon_droid": "sw-death-droid.wav", "sw_unit_ob_cloning_cylinder": "sw-death-glass.wav",
    "sw_unit_ob_cloaked_asteroid": "sw-death-rock.wav", "sw_unit_ob_shield_generator": "sw-death-vehicle.wav",
    "sw_unit_ob_shipyard_platform": "sw-death-capital.wav",
}
MOVE_SOUNDS = {"sw_starfighter": "sw-move-fighter.wav", "sw_capital": "sw-move-capital.wav",
               "sw_repulsor": "sw-move-speeder.wav", "sw_walker": "sw-move-walker.wav"}
STATIONARY = {"sw_unit_ob_cloaked_asteroid", "sw_unit_ob_cloning_cylinder", "sw_unit_ob_shield_generator",
              "sw_unit_ob_shipyard_platform"}


# Installations and objects that neither move nor attack (owner direction
# 2026-10-08): only the animations their art provides are wired. Their other
# frame files stay on disk as copies of the standing frame for the art
# contract, but the unit never plays them.
STATIC_ANIMS = {
    "sw_unit_nr_docked_warship": {"idle", "death"},
    "sw_unit_ob_cloning_cylinder": {"idle", "death"},
    "sw_unit_ob_shipyard_platform": {"idle", "death"},
    "sw_unit_ob_shield_generator": {"idle", "defend", "death"},
    "sw_unit_ob_cloaked_asteroid": {"idle", "defend", "death"},
}


def with_sound(frame_text: str, sound: str | None) -> str:
    return frame_text.replace("\n[/frame]", f"\n    sound={sound}\n[/frame]") if sound else frame_text


def ranged_sound(attack_name: str) -> str | None:
    if attack_name in NO_PROJECTILE:
        return None
    if attack_name == "bow":
        return "bow.ogg"
    if attack_name.startswith("ion_"):
        return "sw-ion.wav"
    if attack_name.startswith("proton_torpedo"):
        return "sw-torpedo.wav"
    if attack_name.startswith("concussion_"):
        return "sw-torpedo.wav"
    if attack_name == "force_lightning":
        return "sw-force-lightning.wav"
    if attack_name == "stun_blaster":
        return "sw-stun.wav"
    if attack_name == "bowcaster":
        return "sw-bowcaster.wav"
    if attack_name in ("turbolasers", "turbo_laser"):
        return "sw-turbolaser.wav"
    if attack_name.endswith("laser_cannons"):
        return "sw-laser-cannon.wav"
    if attack_name in HEAVY_WEAPONS:
        return "sw-blaster-heavy.wav"
    return "sw-blaster.wav"


def melee_anim(base: str, unit_id: str, attack: dict | None) -> str:
    """Wind-up (melee-1) before the strike at time 0, follow-through (melee-2) after it,
    with the weapon's hit or miss sound at the moment of impact."""
    filter_line = "        range=melee" if attack is None else f"        name={attack['name']}"
    impact = MELEE_IMPACTS.get(attack["name"]) if attack else None
    sound = f"    {{SOUND:HIT_AND_MISS {impact[0]} {impact[1]} -25}}\n" if impact else ""
    del unit_id
    return ("[attack_anim]\n    [filter_attack]\n" + filter_line + "\n    [/filter_attack]\n"
            "    start_time=-150\n" + sound
            + indent(frame(f"{base}/melee-1.png", 150), 4) + "\n"
            + indent(frame(f"{base}/melee-2.png", 200), 4) + "\n[/attack_anim]")


def ranged_anim(base: str, unit_id: str, attack: dict | None) -> str:
    """Aim (ranged-1), then fire (ranged-2) as the projectile leaves; it lands at time 0."""
    filter_lines = "        range=ranged\n" if attack is None else f"        name={attack['name']}\n"
    lines = ["[attack_anim]", "    [filter_attack]", filter_lines.rstrip("\n"), "    [/filter_attack]",
             "    start_time=-300"]
    # Aimed variants reuse their base weapon's projectile and sounds.
    key = attack.get("base", attack["name"]) if attack else None
    missile = projectile(unit_id, key) if attack else None
    if missile:
        image, diagonal = missile
        lines += ["    missile_start_time=-150", "    [missile_frame]", "        duration=150",
                  f"        image={image}"]
        if diagonal:
            lines.append(f"        image_diagonal={diagonal}")
        lines.append("    [/missile_frame]")
    fire = frame(f"{base}/ranged-2.png" + (flash_overlay(unit_id, key, missile) if attack else ""), 150)
    sound = ranged_sound(key) if attack else None
    if attack and key == "bow":
        lines.append("    {SOUND:HIT_AND_MISS bow.ogg bow-miss.ogg -150}")
        sound = None
    elif attack and key.startswith("concussion_"):
        lines.append("    {SOUND:HIT_AND_MISS sw-explosion.wav sw-bomb-miss.wav -10}")
    elif attack and key == "deflection":
        lines.append("    {SOUND:HIT_AND_MISS sw-deflect.wav sw-blaster-miss.wav -10}")
    elif sound in RANGED_IMPACTS:
        hit, miss = RANGED_IMPACTS[sound]
        lines.append(f"    {{SOUND:HIT_AND_MISS {hit} {miss} -10}}")
    fire = with_sound(fire, sound)
    return ("\n".join(lines) + "\n" + indent(frame(f"{base}/ranged-1.png", 150), 4) + "\n"
            + indent(fire, 4) + "\n[/attack_anim]")


# Attack icons: original Star Wars icons from production/tools/gen_attack_icons.py
# (sw-*), and mainline icons only where they already fit (fists, fangs, the
# Wayland natives' primitive spears, bows and clubs).
ICONS = {
    "blaster_rifle": "sw-blaster-rifle", "blaster_carbine": "sw-blaster-rifle", "bike_blaster": "sw-blaster-rifle",
    "blaster_pistol": "sw-blaster-pistol", "heavy_blaster_pistol": "sw-heavy-blaster-pistol",
    "hold_out_blaster": "sw-hold-out-blaster", "stun_blaster": "sw-stun-blaster",
    "eweb_repeater": "sw-heavy-repeater", "twin_blaster_cannon": "sw-heavy-repeater",
    "laser_cannons": "sw-laser-cannon", "point_defense": "sw-laser-cannon", "turbolasers": "sw-turbolaser",
    "ion_cannon": "sw-ion-cannon", "ion_cannons": "sw-ion-cannon", "proton_torpedoes": "sw-proton-torpedo",
    "concussion_bombs": "sw-concussion-bomb", "concussion_grenade": "sw-concussion-bomb",
    "plasma_jets": "fire-breath-drake", "lightsaber": "sw-lightsaber-blue", "deflection": "sw-deflection",
    "force_lightning": "sw-force-lightning", "force_pike": "sw-force-pike", "vibroknife": "sw-vibroknife",
    "vibroblade": "sw-vibroblade", "ryyk_blade": "blade-curved", "noghri_knives": "dagger-curved",
    "bowcaster": "sw-bowcaster", "sprayer": "sw-sprayer", "manipulator": "sw-manipulator",
    "rifle_butt": "club-small", "fists": "fist-human", "wookiee_strength": "fist-troll", "stomp": "foot-boot",
    "ram": "ram", "fangs": "fangs-animal", "whip_tail": "tail-jumpcat", "spear": "spear", "bow": "bow",
    "war_club": "club",
}
# Luke's lightsaber is green (the blade he built himself). The novels do not
# fix C'baoth's colour, so his keeps the classic Jedi blue; the clone Luuke's
# published art shows a green blade, and the icon matches the art.
UNIT_ICONS = {("sw_hero_luke", "lightsaber"): "sw-lightsaber-green",
              ("sw_hero_luuke", "lightsaber"): "sw-lightsaber-green"}


# --- weapon ranges and aimed shots (owner design, 2026-10-03) ---------------
# Ranged attacks reach targets up to max_range hexes away (native 1.19
# min_range/max_range). Accuracy falls 10% per hex beyond the first. The
# range is shown as a weapon special ("range N") so it appears with damage
# and strikes in the weapon information.
#   pistols 1, rifles and long arms 2, heavy and crew-served 3; Han Solo's
#   DL-44 heavy blaster pistol is the exception at 2. Bombs drop on the hex
#   beneath (1); guided torpedoes reach 3 without falloff.
#   Jedi blaster deflection reaches 2 (balance review 2026-10-04): it only
#   returns fire, and at 1 a rifleman 2 hexes away shot a Jedi without reply.
WEAPON_RANGES = {
    # infantry
    "blaster_pistol": 1, "hold_out_blaster": 1, "stun_blaster": 1, "sprayer": 1,
    "heavy_blaster_pistol": 2,   # Han Solo's DL-44 (only Han carries it)
    "blaster_rifle": 2, "blaster_carbine": 2, "bowcaster": 2, "bike_blaster": 2, "bow": 2,
    "concussion_grenade": 2, "force_lightning": 2, "deflection": 2,
    "eweb_repeater": 3, "twin_blaster_cannon": 3,
    # craft
    "laser_cannons": 2, "ion_cannon": 2, "point_defense": 1, "concussion_bombs": 1,
    "proton_torpedoes": 3, "turbolasers": 3, "ion_cannons": 3,
}
NO_FALLOFF = {"proton_torpedoes"}       # guided
RANGE_FALLOFF = 10                      # % to hit lost per hex beyond the first
# Aimed shot: one strike fewer, +20% to hit, needs 2+ hexes, attack only.
AIMED_WEAPONS = {"blaster_rifle", "blaster_carbine", "bowcaster", "bow", "heavy_blaster_pistol"}
AIMED_BONUS = 20


def range_special(name: str, max_range: int) -> str:
    if max_range <= 1:
        return (
            "[chance_to_hit]\n"
            "    id=sw_special_range\n"
            "    name= _ \"range 1\"\n"
            "    description= _ \"Close range: only adjacent targets.\"\n"
            "    add=0\n"
            "    cumulative=yes\n"
            "[/chance_to_hit]"
        )
    if name in NO_FALLOFF:
        return (
            "[chance_to_hit]\n"
            "    id=sw_special_range\n"
            f"    name= _ \"range {max_range}, guided\"\n"
            f"    description= _ \"Reaches targets up to {max_range} hexes away. Guided: no accuracy lost with distance.\"\n"
            "    add=0\n"
            "    cumulative=yes\n"
            "[/chance_to_hit]"
        )
    return (
        "[chance_to_hit]\n"
        "    id=sw_special_range\n"
        f"    name= _ \"range {max_range}\"\n"
        f"    description= _ \"Reaches targets up to {max_range} hexes away. Each hex beyond the first lowers the "
        f"chance to hit by {RANGE_FALLOFF}%.\"\n"
        # Special formulas see the combatants as attacker and defender.
        f"    sub=\"({RANGE_FALLOFF} * (distance_between(attacker.loc, defender.loc) - 1))\"\n"
        "    cumulative=yes\n"
        "[/chance_to_hit]"
    )


# Flanking (owner design, 2026-10-04): every weapon gets +FLANK_BONUS% chance to
# hit for each unit hostile to the target standing on the target's far side,
# up to FLANK_MAX%. Defined once as a WML macro in units/00_sw_specials.cfg
# (sorted first in the units directory, so it exists before any unit file
# uses it) and referenced from every attack.
FLANK_BONUS = 10
FLANK_MAX = 20

# Hostile, armed, not petrified units adjacent to the target and farther from
# the attacker than the target is: for a melee attack, the three hexes behind
# the target; for a shot from range, the hexes behind it along the line of
# fire. In a special's [filter_opponent] formula, self and loc are the target
# and other is the attacking unit (installed src/units/filter.cpp).
# Engine details (src/formula): inside filter()/map(), self, loc and other
# names resolve against each list element first, so the target, its hex and
# the attacker's hex are bound up front with sw_-named where variables; WFL
# "and" evaluates both sides, so empty hexes are dropped before unit fields
# are read. The count is followed by the tier test, then the where clause.
FLANKERS_WFL = (
    "size(filter(filter(map(filter(adjacent_locs(sw_here), 'sw_l', "
    "distance_between(sw_l, sw_from) > sw_dist), 'sw_l', unit_at(sw_l)), "
    "'sw_u', sw_u != null()), 'sw_u', enemy_of(sw_target, sw_u) and not sw_u.petrified and size(sw_u.attacks) > 0))"
)
FLANKERS_WHERE = ("where sw_target = self, sw_here = loc, sw_from = other.loc, "
                  "sw_dist = distance_between(loc, other.loc)")


def flanking_specials_wml() -> str:
    """units/00_sw_specials.cfg: the SW_SPECIAL_FLANKING macro."""
    tiers = []
    steps = FLANK_MAX // FLANK_BONUS
    for n in range(1, steps + 1):
        bonus = n * FLANK_BONUS
        test = f"= {n}" if n < steps else f">= {n}"
        tiers.append(
            "    [chance_to_hit]\n"
            "        id=sw_special_flanking\n"
            f"        name= _ \"flanking +{bonus}%\"\n"
            "        # Empty inactive name and description: shown only while it applies.\n"
            "        name_inactive=\"\"\n"
            f"        description= _ \"The target is flanked: allies stand on its far side. +{FLANK_BONUS}% chance to "
            f"hit for each, up to +{FLANK_MAX}%.\"\n"
            "        description_inactive=\"\"\n"
            f"        add={bonus}\n"
            "        cumulative=yes\n"
            "        active_on=offense\n"
            "        [filter_opponent]\n"
            f"            formula=\"({FLANKERS_WFL} {test}) {FLANKERS_WHERE}\"\n"
            "        [/filter_opponent]\n"
            "    [/chance_to_hit]\n"
        )
    return (
        HEADER
        + "\n"
        "# Weapon specials shared by every unit file. Named 00_* so the directory\n"
        "# include loads it first: a macro must be defined before it is used.\n"
        "\n"
        "# Flanking: when attacking, +10% chance to hit for each unit hostile to the\n"
        "# target that stands adjacent to it on its far side -- farther from the\n"
        "# attacker than the target is (for a melee attack, the three hexes behind\n"
        "# the target). At most +20%. Petrified and unarmed units do not count, and\n"
        "# it never applies to return fire. One special per tier, so the attack\n"
        "# dialog names the exact bonus, and neither is listed when inactive.\n"
        "#define SW_SPECIAL_FLANKING\n"
        + "".join(tiers)
        + "#enddef\n"
    )


def aimed_special() -> str:
    return (
        "[chance_to_hit]\n"
        "    id=sw_special_aimed\n"
        "    name= _ \"aimed shot\"\n"
        f"    description= _ \"Taking a moment to aim: one shot fewer, +{AIMED_BONUS}% chance to hit. Needs at least two "
        "hexes of distance (no time to aim at point-blank range) and can only be used when attacking.\"\n"
        f"    add={AIMED_BONUS}\n"
        "    cumulative=yes\n"
        "[/chance_to_hit]\n"
        "[disable]\n"
        "    id=sw_special_aimed_attack_only\n"
        "    active_on=defense\n"
        "[/disable]"
    )


def expanded_attacks(u: dict) -> list[dict]:
    """The unit's attacks with ranges applied and aimed-shot variants added
    right after the weapons that have one."""
    out = []
    for a in u["attacks"]:
        a = dict(a)
        if a["range"] == "ranged":
            a["max_range"] = WEAPON_RANGES.get(a["name"], a.get("max_range") or 1)
        out.append(a)
        if a["range"] == "ranged" and a["name"] in AIMED_WEAPONS and a["max_range"] >= 2 and a["number"] >= 2:
            aimed = dict(a)
            aimed.update(name=a["name"] + "_aimed", desc=a["desc"] + " (aimed)", number=a["number"] - 1,
                         base=a["name"], min_range=2, aimed=True)
            out.append(aimed)
    return out


def attack_wml(a: dict, unit_slug: str, unit_id: str = "") -> str:
    lines = [
        "[attack]",
        f"    name={a['name']}",
        f"    description= _ \"{a['desc']}\"",
        f"    icon=attacks/{UNIT_ICONS.get((unit_id, a.get('base', a['name'])), ICONS.get(a.get('base', a['name']), 'blank-attack'))}.png",
        f"    type={a['type']}",
        f"    range={a['range']}",
        f"    damage={a['damage']}",
        f"    number={a['number']}",
    ]
    if a.get("max_range"):
        lines.append(f"    min_range={a.get('min_range', 1)}")
        lines.append(f"    max_range={a['max_range']}")
    blocks = [SPECIALS[sp] for sp in a["specials"]]
    if a["range"] == "ranged" and a.get("max_range"):
        blocks.append(range_special(a.get("base", a["name"]), a["max_range"]))
    if a.get("aimed"):
        blocks.append(aimed_special())
    blocks.append("{SW_SPECIAL_FLANKING}")
    if blocks:
        lines.append("    [specials]")
        for block in blocks:
            lines.append(indent(block, 8))
        lines.append("    [/specials]")
    lines.append("[/attack]")
    del unit_slug
    return "\n".join(lines)


# Unarmed variations (owner direction 2026-10-06): a hero who loses his weapon
# in a mission shows his own unarmed sprite set until he recovers it. The
# variation is the full unit (inherit=no, so no positional merging of
# animations) with its art in units/<slug>-unarmed/ and an animation for the
# fists the mission's object gives him. Scenarios switch it with the
# SW_UNARMED / SW_ARMED macros (utils/hte_macros.cfg).
UNARMED_VARIATIONS = {"sw_hero_luke": "fists"}


def unarmed_variation(u: dict) -> str:
    s = slug(u["id"])
    art = f"{s}-unarmed"
    body = unit_wml(u, with_variations=False).replace(f"units/{s}/", f"units/{art}/").split("\n")
    body = [line for line in body[1:-1] if not line.startswith("    id=")]
    melee = melee_anim(f"units/{art}", u["id"], {"name": UNARMED_VARIATIONS[u["id"]]})
    return "\n".join(["[variation]", "    variation_id=unarmed", "    variation_name= _ \"unarmed\"",
                      "    hide_help=yes", "    inherit=no"] + body + [indent(melee, 4), "[/variation]"])


def unit_wml(u: dict, with_variations: bool = True) -> str:
    s = slug(u["id"])
    lines = [
        "[unit_type]",
        f"    id={u['id']}",
        f"    name= _ \"{u['name']}\"",
        f"    race={u['race']}",
    ]
    if u["gender"]:
        lines.append(f"    gender={u['gender']}")
    lines += [
        f"    image=units/{s}/standing.png",
        f"    profile=portraits/{s}.png",
        f"    hitpoints={u['hp']}",
        f"    movement_type={u['mt']}",
        f"    movement={u['mp']}",
        f"    experience={u['xp']}",
        f"    level={u['level']}",
        f"    alignment={u['alignment']}",
        f"    advances_to={u['advances'] or 'null'}",
        f"    cost={u['cost']}",
        f"    usage={u['usage']}",
        f"    description= _ \"{u['desc']}\"",
    ]
    if u["advances"] is None:
        lines.append("    {AMLA_DEFAULT}")
    if u["zoc"] == "no":
        lines.append("    zoc=no")
    if u["hero"]:
        lines.append("    # Named character: scenarios place the single instance and keep")
        lines.append("    # it out of recruit lists.")
        lines.append("    do_not_list=yes")
    system_abilities = [x for x in (force_ability(u["id"]), overwatch_ability(u["attacks"]), ew_ability(u["id"]),
                                    observer_ability(u["id"]), anti_air_ability(u["id"])) if x]
    if u["abilities"] or system_abilities:
        lines.append("    [abilities]")
        for ab in u["abilities"]:
            lines.append(indent(ABILITY_BUILDERS[ab](), 8))
        for block in system_abilities:
            lines.append(indent(block, 8))
        lines.append("    [/abilities]")
    for a in expanded_attacks(u):
        lines.append(indent(attack_wml(a, s, u["id"]), 4))
    lines.append(indent(animations(u), 4))
    if u["id"] in FLYOVER_CRAFT and with_variations:
        lines.append(indent(flyover_variation(), 4))
    if u["id"] in UNARMED_VARIATIONS and with_variations:
        lines.append(indent(unarmed_variation(u), 4))
    lines.append("[/unit_type]")
    return "\n".join(lines)


def movetypes_wml() -> str:
    out = [HEADER, "# Movement types and races shared by Campaign I units.",
           "# Defense values are the chance to be hit; resistance is percent damage taken.", ""]
    for rid, (name, plural, desc) in RACES.items():
        out += [
            "[race]",
            f"    id={rid}",
            f"    name= _ \"race^{name}\"",
            f"    plural_name= _ \"race^{plural}\"",
            f"    description= _ \"{desc}\"",
            "    num_traits=2",
            "    ignore_global_traits=no",
            "[/race]",
            "",
        ]
    for mid, spec in MOVETYPES.items():
        flies = spec.get("flies", False)
        out += [f"# {spec['doc']}", "[movetype]", f"    name={mid}"]
        if flies:
            out.append("    flies=yes")
        out.append("    [movement_costs]")
        out += [f"        {t}={spec['move'].get(t, UNREACHABLE)}" for t in TERRAINS]
        out.append("    [/movement_costs]")
        out.append("    [defense]")
        out += [f"        {t}={spec['defense'][t]}" for t in TERRAINS]
        out.append("    [/defense]")
        out.append("    [resistance]")
        out += [f"        {k}={v}" for k, v in spec["resist"].items()]
        out.append("    [/resistance]")
        out += ["[/movetype]", ""]
    return "\n".join(out)


def render() -> dict[str, str]:
    files: dict[str, str] = {"00_sw_specials.cfg": flanking_specials_wml(), "hte_00_movetypes.cfg": movetypes_wml()}
    for fname, doc in FILES.items():
        units = [u for u in ROSTER if u["file"] == fname]
        body = [HEADER, f"# {doc}", ""]
        body += [unit_wml(u) + "\n" for u in units]
        files[f"{fname}.cfg"] = "\n".join(body)
    files["../lua/sw_rank_data.lua"] = rank_data_lua()
    return files


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args()
    ids = [u["id"] for u in ROSTER]
    if len(ids) != len(set(ids)):
        raise SystemExit("duplicate unit id in roster")
    stale = []
    for name, text in render().items():
        path = UNITS_DIR / name
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != text:
                stale.append(name)
        else:
            path.write_text(text, encoding="utf-8")
    if stale:
        print("stale generated unit files: " + ", ".join(stale), file=sys.stderr)
        return 1
    print(f"{'checked' if args.check else 'wrote'} {len(ROSTER)} unit types")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
